   var GAME_LEVELS = [
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                y ",
   "                                                                                                                y ",
   "                                                                     o                                          y ",
   "   o                                                                                                          o y ",
   "           o                                                       yyyyy                                        y ",
   "  yyy                   o                                                                                       y ",
   "                                                                               yyyy                        yyyyyy ",
   "         yyyyy                                      oo                                                            ",
   "                           >                                                                                      ",
   "                                                                                  >                               ",                                                                           
   "    ^            yyyyy                 y        o yyyyyy                                                          ",
   "                                       y          y                                           >                   ",
   "      >      o                         y       yyyy              >                 o                              ",
   "                                       y          y                                                               ",
   "          yyyyy                        y o        y                                                    ^          ",
   "                                       y          y                                                               ",
   " @                                     yyyy       y                            >                                  ",
   " yyyy!!!yy                             y          y                                                               ",
   "    y!!!!y                             y        o y                                                               ",
   "    y!!!!y                             y          y                                                               ",
   "    yyyyyy                             y       yyyy      ^                                                        ",
   "                                                  y                                                               ",
   "                                                  y                                                               ",
   "                                          >       y        xxx xxx xxxx          xxxxx  xx     xxxxxx x    xx  xx ",
   "  yyyyyyyyyyyyy   yyyyy                           y      yyyyyyyyyyyyy           yyyyyyyyy     yyyyyyyy    yyyyyy ",
   "                      y                           y                                                               ",     
   "              o       y                           y                                                               ",   
   "                      y                           y                                                               ",
   "        o   yyyyyy    y      >                    y                                                               ",
   "                      y                           y                                                               ",
   "       yyyy           yxxxxxxxxxxxxxxxxxxxxxxxxxxxy                                                               ",
   "                      yyyyyyyyyyyyyyyyyyyyyyyyyyyyy                                                               ",
   " yyyy                                                                                                             ",
   "             o                     o                      o              o                      o                 ",
   "                                                                  ?                 ?                             ",
   "yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy"],
  
  
  
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   o            ",
   "                   o                                                            ",
   "                                                                  yyy           ",
   "                  yyy                              yyy    yyy    yy!yy          ",
   "                                    o o      yyyy               y!!!!!y         ",
   "                                                                 yy!yy          ",
   "                                   yyyyy                          yvy           ",
   "            yy                                                              yy  ",
   "  yy           o                          o o                                y  ",
   "  y    yy               o                                                    y  ",
   "  y         yyyyyy                        yyyyy                    o       o y  ",
   "  y         y                    o                                           y  ",
   "  y @       y          y                         x   xx             yyyyy       y  ",
   "  yyyy  yyyyyyy  yyyyyyyyyyyyyyy   yyyyyyyyyyyyyyyyyyyy     yyyyyyyyyyyyyyyyyy  ",
   "     y!!y     y!!y             y   y                  y     y                   ",
   "     y!!y     yyyy             y!!!y                  y!!!!!y                   ",
   "     yyyy                      y!!!y                  y!!!!!y                   ",
   "                               yyyyy                  yyyyyyy                   ",
   "                                                                                ",
   "                                                                                "],

   
   
  ["                                                  o                                                                          ",
   "                                                                                          o                                  ",
   "  o                              >>>>>>>                                                                                     ",
   "yyyyy                                                                                                                        ",
   "                    yyyy                                                                                                     ",
   "                                                        yyyyyyyyy  yyy  yyyyy                                    yyyyyyyyyy  ",
   "                                                        y!!y            y!!!y                                       o o o y  ",
   "                                                        y!!!y         yy!!!!y                                    yyyyyyyyyy  ",
   "             >>>>>                                      y!!!!y       y!!!!!!y                >>>>>>>>                        ",
   "                                                        y!!!!!y     y!!!!!!!y                                                ",
   "                                o                       y!!!!!!y   y!!!!!!!!y                                                ",
   "                                                        y!!!!!!!yoy!!!!!!!!!y       ^^^^^^^                                  ",
   "                             yyyyyyy                    y!!!!!!!yyy!!!!!!!!!y                                                ",
   "                                                        y!!!!!!!!!!!!!!!!!!!y                                                ",
   "                                          o             y!!!!!!!!!!!!!!!!!!!y                                                ",
   "                                                        y!!!!!!!!!!!!!!!!!!!y                                                ",
   "                   >>>>>>                               yyyyyyyyyyyyyyyyyyyyy                 yyyyyyy                        ",
   "                                                         yyyyyyyyyyyyyyyyyyy                                                 ",
   "                                                          yyyyyyyyyyyyyyyyy                                                  ",
   "                                                           yyyyyyyyyyyyyyy                                                   ",
   "                                                           y                                                                 ",
   "           yyyyyyyyyyy                 ^^^^^^              y                                                                 ",
   "                                                           yo                                         ^^^^^^                 ",
   "                                                           y                                                                 ",
   "                                                           yxx                                                               ",
   "                                                           yyyyyyy     y                                                     ",
   "                                                           !!!!!!y                                                           ",
   "                                                           !!!!!!yyyyyyyyy                                                   ",
   "  o                                                        !!!!!!!!!!!!!!y                   yyyyy                           ",
   "yyyyyy                                                     !!!!!!!!!!!!!!y                                                   ",
   "                                                           !!!!!!!!!!!!!!y                                                   ",
   "                                                           !!!!!!!!!!!!!!y       yyyyyy                                      ",
   "                                                           yyyyyyyyyyyyyyy                                                   ",
   "                                                           y o o o o o o                                                     ",
   "                                                           y                                                                 ",
   "                                                           yyyyyyyyyyyyyyyy                                                  ",
   "                                                                                                                             ",
   "                        xxxx                      ?                                 xxxx              ?             xxxxxxxxx",
   "yyyyyyyyyyyyyyyyxxxyyyyyyyyyyyyyyy     yyyyyyyyyyyyyyyyyyyyyy      yyyyyyyyyyyyyyyyyyyyyyyy      yyyyyyyyyyyyyyyyyyyyyyyyyyyy",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
   
  
];

if (typeof module != "undefined" && module.eyports)
  module.eyports = GAME_LEVELS;
